### ISSUE TITLE
Error during init of new application

### ISSUE THREAD

**Issue by josegonzalez** [briandilley/ebs-deploy#15]
I configured my `ebs.config` as it says in the readme, but I get the following consistent error:

```
Creating application haldane
Creating environment: Haldane-Prod, tier_name:WebServer, tier_type:Standard
Traceback (most recent call last):
  File ".virtualenv/bin/ebs-deploy", line 81, in <module>
    main()
  File ".virtualenv/bin/ebs-deploy", line 75, in main
    exit(command.execute(helper, config, args))
  File "/vagrant/.virtualenv/local/lib/python2.7/site-packages/ebs_deploy/commands/init_command.py", line 39, in execute
    version_label=args.version_label)
  File "/vagrant/.virtualenv/local/lib/python2.7/site-packages/ebs_deploy/__init__.py", line 293, in create_environment
    tier_version=tier_version)
  File "/vagrant/.virtualenv/local/lib/python2.7/site-packages/boto/beanstalk/layer1.py", line 357, in create_environment
    return self._get_response('CreateEnvironment', params)
  File "/vagrant/.virtualenv/local/lib/python2.7/site-packages/boto/beanstalk/layer1.py", line 71, in _get_response
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.BotoServerError: BotoServerError: 400 Bad Request
{"Error":{"Code":"InvalidParameterValue","Message":"No application version exists to deploy for Application named haldane.","Type":"Sender"},"RequestId":"53ccde20-5c7d-11e4-b343-4568be2697be"}
```

**Comment by josegonzalez** [comment]
Any luck figuring out what I may have done wrong?

**Comment by josegonzalez** [comment]
If it helps, I can share the app I'm attempting to deploy :)

**Comment by briandilley** [comment]
What command are you running

**Comment by josegonzalez** [comment]
`ebs-deploy init` is the command I run.

**Comment by ixaxaar** [comment]
+1 encountered the same problem, boto seems to do this:
here https://github.com/briandilley/ebs-deploy/blob/master/ebs_deploy/__init__.py#L313

```
VersionLabel (string) --
The name of the application version to deploy.

If the specified application has no associated application versions, AWS Elastic Beanstalk UpdateEnvironment returns an InvalidParameterValue error.

Default: If not specified, AWS Elastic Beanstalk attempts to launch the sample application in the container.
```

**Comment by ballpointcarrot** [comment]
In the config file provided by @josegonzalez, the Solution Stack name provided has `v1.0.91`, which isn't a provided Solution Stack by EB. This error will come up when providing a Solution Stack name that EB doesn't know about.

Check your provided Solution Stack name; if correct, it should default to deploying the sample app (as @ixaxaar mentioned) if there is no provided application version.
